/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package fr.ufrsciencestech.panier;

import java.awt.Dimension;
import java.awt.Button;
import java.awt.Label;
import java.util.Observable;

/**
 *
 * @author richa
 */
public class VueGAWT extends java.awt.Frame implements VueGraphique{

    /**
     * Creates new form VueGAWT
     */
    public VueGAWT() {
        initComponents();
        //position centrée de la fenêtre
        this.setLocationRelativeTo(null);
        //dimensions
        this.setPreferredSize(new Dimension(500,500));
        //titre
        this.setTitle("Panier");
        //définition d'un nom pour les deux boutons de la fenêtre
        this.inc.setName("Plus");
        this.dec.setName("Moins");
        this.pack();
        this.setVisible(true);
    }
    
    //accesseurs et mutateurs
    public Button getInc()
    {
        return this.inc;
    }
    
    public Button getDec()
    {
        return this.dec;
    }
    
    public Label getAffiche()
    {
        return this.affiche;
    }
    
    public void setAffiche(Label affiche)
    {
        this.affiche = affiche;
    }
    
    @Override
    public void ajouteControleur(Controleur c)
    {
        this.getInc().addActionListener(c);
        this.getDec().addActionListener(c);
    }
    
    @Override
    public void update (Observable o, Object arg)
    {
        this.getAffiche().setText(((Integer)arg).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        affiche = new java.awt.Label();
        inc = new java.awt.Button();
        dec = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        affiche.setAlignment(java.awt.Label.CENTER);
        add(affiche, java.awt.BorderLayout.CENTER);

        inc.setLabel("+");
        add(inc, java.awt.BorderLayout.NORTH);

        dec.setLabel("-");
        add(dec, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VueGAWT().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label affiche;
    private java.awt.Button dec;
    private java.awt.Button inc;
    // End of variables declaration//GEN-END:variables
}
